In [1]:
import platform
platform.uname()

uname_result(system='Windows', node='Laptop_HSoni', release='10', version='10.0.17134', machine='AMD64', processor='Intel64 Family 6 Model 37 Stepping 5, GenuineIntel')

In [2]:
platform.python_version()

'3.7.2'

In [3]:
import numpy as np
print("NumPy Version:",np.__version__)

NumPy Version: 1.15.4


# Basics of NumPy Array Object

Arrays can be created in several ways. One of them is to use the array function to turn a list into an array:
```python
np.array(list,type)
```

In [4]:
x = np.array([range(k, k+3) for k in [2, 5]])
x  # Two-dimensional array

array([[2, 3, 4],
       [5, 6, 7]])

In [5]:
print("We just create a ", type(x).__name__)

We just create a  ndarray


In [6]:
print("Our template has shape as" ,x.shape)

Our template has shape as (2, 3)


In [7]:
print("Total size is",x.size)

Total size is 6


In [8]:
print("The dimension of our array is " ,x.ndim)

The dimension of our array is  2


In [9]:
print("Data type of elements are",x.dtype)

Data type of elements are int32


In [10]:
print("It consumes",x.nbytes,"bytes")

It consumes 24 bytes


In [11]:
# x = np.array([range(k, k+3) for k in [2, 5]], float)
x = np.array([range(k, k+3) for k in [2, 5]], dtype=np.float)
print(x)
print(x.nbytes)

[[2. 3. 4.]
 [5. 6. 7.]]
48


In [12]:
# x = np.array([range(k, k+3) for k in [2, 5]], 'uint32')
x = np.array([range(k, k+3) for k in [2, 5]], dtype=np.uint32)
print(x)
print(x.nbytes)

[[2 3 4]
 [5 6 7]]
24


Observe that each type consumes a different number of bytes. Hence, it is advisable to declare data type carefully while creating an array. 


Imagine you are creating a matrix of shape (100000, 100) as follows: 

In [13]:
data = np.random.rand(100000,100)
print("You created a ", type(data).__name__)
print("dtype:", data.dtype)
print("itemsize:", data.itemsize, "bytes")
print("nbytes:", data.nbytes)
# data_new = np.array(data, dtype = np.float32)
data_new = data.astype(np.float32)
print("*****After Changing data type*****")
print("dtype:", data_new.dtype)
print("itemsize:", data_new.itemsize, "bytes")
print("nbytes:", data_new.nbytes)

You created a  ndarray
dtype: float64
itemsize: 8 bytes
nbytes: 80000000
*****After Changing data type*****
dtype: float32
itemsize: 4 bytes
nbytes: 40000000


As you can see from the preceding code, the size decreases from 80 MB to 40 MB just by
changing the `dtype`. What we get in return is less precision after decimal points. Instead of
being precise to 16 decimals points, you will have only 7 decimals.


In general, we expect that `nbytes` is equal to `itemsize` times `size`.


Visit https://docs.scipy.org/doc/numpy-1.13.0/user/basics.types.html to refer Standard NumPy data types.


**Note:** you cannot change the dtype after you create the array. However, what you can do is either create it again or copy the existing one with a new dtype and with the `astype` attribute.

## Array Creation Functions

- **`np.arange()`** Produces an array containing the specified values, acting as an array version of `range()`.

- **`np.ones()`** Produces an array containing all ones.

- **`np.zeros()`** Similar to `np.ones()`, except that all elements of the matrix are zero.

- **`np.eye()`** Produces the identity matrix. 

- **`np.linspace(start,stop,npoints)`** Produces a matrix with linearly spaced elements. The nice thing is that you specify the number of elements, not the spacing.

In [14]:
x = np.arange(1, 10, 2)
print('array:', x)
print('dtype:', x.dtype)

array: [1 3 5 7 9]
dtype: int32


In [15]:
# it accepts float arguments
x = np.arange(0, 1, 0.1)
print('array:', x)
print('dtype:', x.dtype)

array: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
dtype: float64


In [16]:
# by specifying dtype
x = np.array(np.arange(0, 1, 0.1), dtype=np.float32)
print('array:', x)
print('dtype:', x.dtype)

array: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
dtype: float32


In [17]:
x = np.arange(0, 1, 0.1, dtype=np.float32)
x

array([0.        , 0.1       , 0.2       , 0.3       , 0.4       ,
       0.5       , 0.6       , 0.7       , 0.8       , 0.90000004],
      dtype=float32)

In [18]:
x = np.ones(3)
print('array:', x)
print('dtype:', x.dtype)

array: [1. 1. 1.]
dtype: float64


In [19]:
# Two-dimensional array
x = np.ones((3,4))
print('array:', x)
print('dtype:', x.dtype)

array: [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
dtype: float64


In [20]:
# You can specify the type of arrays
x = np.ones((3,4),dtype=np.float32)
print('array:', x)
print('dtype:', x.dtype)

array: [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
dtype: float32


In [21]:
# Three-dimensional array
x = np.ones((3,4,5))
x

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [22]:
# You can specify the type of arrays
x = np.zeros((3,4),dtype=np.float32)
print('array:', x)
print('dtype:', x.dtype)

array: [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
dtype: float32


In [23]:
# x = np.eye(3)
x = np.eye(3,dtype=np.float32)
print('array:', x)
print('dtype:', x.dtype)

array: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
dtype: float32


In [24]:
# 10 elements with uniformly distributed values
x = np.linspace(0, 0.9, 10) 
print('array:', x)
print('dtype:', x.dtype)

array: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
dtype: float64


In [25]:
# 10 elements with uniformly distributed values
x = np.linspace(0, 0.9, 10, dtype=np.float32) 
print('array:', x)
print('dtype:', x.dtype)

array: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
dtype: float32


## Changing Array Dimensions/Shape 

The **`reshape`** method or the **`shape`** attribute is used both to set and read the array dimensions:

In [26]:
x = np.array([0, 1.5, 3, -8.5, 6, 9])

In [27]:
# turn x into a 2x3 matrix
x.shape = (2, 3)
x

array([[ 0. ,  1.5,  3. ],
       [-8.5,  6. ,  9. ]])

In [28]:
# turn x into a vector of length 6 again
x.shape = (x.size,)
x

array([ 0. ,  1.5,  3. , -8.5,  6. ,  9. ])

In [29]:
# x = x.reshape(2, 3)  same effect as setting x.shape
y = np.reshape(x, (2, 3))
y

array([[ 0. ,  1.5,  3. ],
       [-8.5,  6. ,  9. ]])

One nice thing about **`np.reshape()`** is that you can use '-1' for 1 dimension within the reshape command to mean "as many as is required". This saves you doing the multiplication yourself.

The criterion to satisfy for providing the new shape is that *'The new shape should be compatible with the original shape'.* 

*numpy* allow us to give one of new shape parameter as -1 (eg: (2,-1) or (-1,3) but not (-1, -1)). It simply means that it is an unknown *dimension* and we want numpy to figure it out. And numpy will figure this by looking at the *'length of the array and remaining dimensions'* and making sure it satisfies the above mentioned criteria. 

In [30]:
x = np.arange(1, 13).reshape(3, 4)
print("shape: ", x.shape)
x
# As new shape (3, 4) is compatible with original shape (12,)

shape:  (3, 4)


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [31]:
# you don't need to determine second dimension
# We have provided rows as 3 but columns as unknown .
x = np.arange(1, 13).reshape(3, -1)
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [32]:
# We have provided column as 3 but rows as unknown .
x = np.arange(1, 13).reshape(-1, 3)
x

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [33]:
# row vector/matrix
x = x.reshape(-1, 1)
print(x)
print('shape:', x.shape)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]
shape: (12, 1)


In [34]:
# column vector/matrix
x = x.reshape(1, -1)
print(x)
print('shape:', x.shape)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]]
shape: (1, 12)


**`np.ravel(x)`** Makes the array one-dimensional.

In [35]:
x = np.arange(1, 13).reshape(3, -1)
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [36]:
x = np.ravel(x)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [37]:
x.shape

(12,)

In [38]:
x = x.ravel()
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [39]:
x.shape

(12,)

**`np.transpose(x)`** Compute the matrix transpose.

In [40]:
x = np.arange(1, 13).reshape(3, -1)
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [41]:
x_T = np.transpose(x)
x_T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [42]:
x_T = x.transpose()
x_T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [43]:
x_T = x.T
x_T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])