In [1]:
import platform
platform.uname()

uname_result(system='Windows', node='Laptop_HSoni', release='10', version='10.0.17134', machine='AMD64', processor='Intel64 Family 6 Model 37 Stepping 5, GenuineIntel')

In [2]:
platform.python_version()

'3.7.2'

In [3]:
import numpy as np
print("NumPy Version:",np.__version__)

NumPy Version: 1.15.4


# NumPy Array indexing, slicing, stride


Indexing, slicing and stride of one-dimensional Numerical Python arrays follows the syntax of Python lists. Refer https://notebooks.azure.com/HNSoni/projects/PyBa/html/Lists.ipynb . 

Keep in mind that, unlike Python lists, NumPy arrays have a fixed type. This means, for example, that if you attempt to insert a floating-point value to an integer array, the value will be silently truncated.


In [4]:
np.random.seed(0) # seed for reproducibility
x1 = np.random.randint(10, size=6) # One-dimensional array
x1

array([5, 0, 3, 3, 7, 9])

In [5]:
x1[3] = 3.14159  # this will be truncated!
x1

array([5, 0, 3, 3, 7, 9])

In [6]:
# set all elements of a equal to 0
x1[:] = 0
x1

array([0, 0, 0, 0, 0, 0])

In [7]:
# set all elements of a equal to 1
x1.fill(1)
x1

array([1, 1, 1, 1, 1, 1])

## Working with Multi-Dmensional array

An extended subscripting syntax is offered for multi-dimensional arrays:

- **`x[i, j]`**  &emsp;&emsp;&emsp; Element at $i^{th}$ row and $j^{th}$ column

- **`x[i, j] = 10`** &emsp; Assignment to element (i,j)

- **`x[i][j] = 10`** &emsp; Equivalent syntax (slower)

- **`x[:, k]`**  &emsp;&emsp;&emsp; Column with index $k$

- **`x[k, :]`** &emsp;&emsp;&emsp;  Row with index $k$

- **`x[:, :] = 0`** &emsp;  Set all elements of a equal to 0

- **`x[::-1]`** &emsp;&emsp;&emsp; Reverse the elements of each dimension

In [8]:
x2 = np.random.randint(10, size=(3, 4)) # Two-dimensional array
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [9]:
# modify some values
x2[1, 3] = 9
x2[2, 2] = 3
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 9],
       [1, 6, 3, 7]])

In [10]:
x2[:2, :3] # two rows, three columns

array([[3, 5, 2],
       [7, 6, 8]])

In [11]:
x2[:3, ::2] # all rows, every other column

array([[3, 2],
       [7, 8],
       [1, 3]])

In [12]:
x2[::-1]

array([[1, 6, 3, 7],
       [7, 6, 8, 9],
       [3, 5, 2, 4]])

In [13]:
# subarray dimensions can even be reversed together
x2[::-1, ::-1]

array([[7, 3, 6, 1],
       [9, 8, 6, 7],
       [4, 2, 5, 3]])

In [14]:
x2[0]  # equivalent to x2[0, :]

array([3, 5, 2, 4])

In [15]:
# Change part of a row
print(x2)
x2[2,0:2] = [8,5]
x2

[[3 5 2 4]
 [7 6 8 9]
 [1 6 3 7]]


array([[3, 5, 2, 4],
       [7, 6, 8, 9],
       [8, 5, 3, 7]])

In [16]:
# In advanced indexing,the first part indicates the index of rows to be sliced and 
# the second part indicates the corresponding columns.
row = np.array([0,1,2])
col = np.array([0,1,3])
x2[row, col]
# x2[[0,1,2],[0,1,3]]

array([3, 6, 7])

In [17]:
# combine fancy indexing with slicing
print(x2)
x2[1:, [2, 0, 1]]

[[3 5 2 4]
 [7 6 8 9]
 [8 5 3 7]]


array([[8, 7, 6],
       [3, 8, 5]])

## Loops over Arrays 

In [18]:
for r_ix in np.arange(x2.shape[0]):
    for c_ix in np.arange(x2.shape[1]):
        print(f"Value at index [{r_ix}, {c_ix}] is {x2[r_ix, c_ix]}")

Value at index [0, 0] is 3
Value at index [0, 1] is 5
Value at index [0, 2] is 2
Value at index [0, 3] is 4
Value at index [1, 0] is 7
Value at index [1, 1] is 6
Value at index [1, 2] is 8
Value at index [1, 3] is 9
Value at index [2, 0] is 8
Value at index [2, 1] is 5
Value at index [2, 2] is 3
Value at index [2, 3] is 7


In [19]:
for e in x2:
    print(e)

[3 5 2 4]
[7 6 8 9]
[8 5 3 7]


In [20]:
# Iterating over all elements
for e in x2.flat:
    print(e, end=' ')

3 5 2 4 7 6 8 9 8 5 3 7 

# Array Concatenation and Splitting

It’s also possible to combine multiple arrays into one, and to conversely split a single array into multiple arrays.

We’ll take a look at those operations here.

In [21]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [22]:
np.r_[x,y]

array([1, 2, 3, 3, 2, 1])

In [23]:
grid = np.array([[1, 2, 3],[4, 5, 6]])
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
# concatenate along the first axis
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [25]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

For working with arrays of mixed dimensions, it can be clearer to use the **`np.vstack`** (vertical stack) and **`np.hstack`** (horizontal stack) functions:

In [26]:
# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [27]:
# equivalent to vstack
x = np.array([[1, 2, 3]])
np.r_[x,grid]

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [28]:
# horizontally stack the arrays
y = np.array([[99], [99]])
np.hstack([grid, y])

array([[ 1,  2,  3, 99],
       [ 4,  5,  6, 99]])

In [29]:
# equivalent to hstack
np.c_[grid,y]

array([[ 1,  2,  3, 99],
       [ 4,  5,  6, 99]])

**`np.r_[]`** and **`np.c_[]`** Perform row and column concatenation, including the use of the slice operator:

There is also a variation on `np.linspace()` using a `j` in the last entry. The j on the last value specifies that you want 3 equally spaced points starting at 0 and running up to (and including) 7, and the function works out the locations of these points for you.

In [30]:
np.r_[1:4,0,4]

array([1, 2, 3, 0, 4])

In [31]:
np.r_[1:11:2]

array([1, 3, 5, 7, 9])

In [32]:
np.r_[2,1:7:3j]

array([2., 1., 4., 7.])

In [33]:
np.c_[np.array([1,2,3]), np.array([4,5,6])]

array([[1, 4],
       [2, 5],
       [3, 6]])

**`np.c_[]`** add along second axis, i.e. column. In above, shape of both array is `(3,1)`. So resultant shape would be `(3,1+1)` which is `(3,2)`.  

In [34]:
np.c_[np.array([1,2,3]), np.array([4,5,6]), np.arange(7, 10)]

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

## Splitting of arrays

The opposite of concatenation is splitting, which is implemented by the functions **`np.split`**, **`np.hsplit`**, and **`np.vsplit`**. For each of these, we can pass a list of indices giving the split points:

In [35]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [36]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [37]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [38]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
